/** Real worker/controllers with explicitly simulated Chrome APIs. Not installed-browser E2E. */
import test from 'node:test';
import assert from 'node:assert/strict';
const event=()=>({listeners:[],addListener(fn){this.listeners.push(fn)},removeListener(fn){this.listeners=this.listeners.filter(f=>f!==fn)}});
const copy=x=>structuredClone(x),stores={local:{},session:{}};
const storage=name=>({setAccessLevel:async()=>{},get:async k=>k==null?copy(stores[name]):Object.fromEntries((Array.isArray(k)?k:[k]).filter(k=>k in stores[name]).map(k=>[k,copy(stores[name][k])])),set:async v=>Object.assign(stores[name],copy(v)),remove:async keys=>{for(const k of(Array.isArray(keys)?keys:[keys]))delete stores[name][k];}});
const id='testanchorabcdefghijklmnopqrstuv';
let tabs=[],windows=[],nextTab=100,nextWindow=10,createdTabs=[],createdWindows=[],moved=[],updates=[],badge=[],ack='ok',failure='',permission=false;
const findTab=id=>{const t=tabs.find(t=>t.id===id);if(!t)throw new Error('No tab');return t;};
const findWindow=id=>{const w=windows.find(w=>w.id===id);if(!w)throw new Error('No window');return w;};
function reindex(){for(const w of windows)tabs.filter(t=>t.windowId===w.id).forEach((t,i)=>t.index=i);}
function moveTab(t,windowId){const old=t.windowId;t.windowId=windowId;reindex();if(!tabs.some(v=>v.windowId===old))windows=windows.filter(w=>w.id!==old);}
function createTab(props){const t={id:nextTab++,url:props.url||'chrome://newtab/',title:'Opened page',index:0,pinned:false,active:true,incognito:false,windowId:props.windowId,token:'document-'+nextTab,scroll:0,...props};tabs.push(t);createdTabs.push(copy(t));reindex();return t;}
globalThis.chrome={
 runtime:{id,getURL:p=>`chrome-extension://${id}/${p}`,getManifest:()=>({version:'2.0.0'}),onMessage:event(),onInstalled:event(),onStartup:event()},
 storage:{local:storage('local'),session:storage('session')},
 tabs:{query:async q=>copy(tabs.filter(t=>(q.windowId===undefined||t.windowId===q.windowId)&&(!q.active||t.active))),get:async id=>copy(findTab(id)),
 create:async p=>{if(failure==='tab-before')throw new Error('API failure');const t=createTab(p);return copy(t);},
 move:async(id,p)=>{if(failure==='move-before')throw new Error('Move failed before attachment');const t=findTab(id);moved.push({id,...p});moveTab(t,p.windowId);return copy(t);},
 update:async(id,p)=>{const t=findTab(id);updates.push({id,...p});if(p.url){t.token='navigated';t.url=p.url;}Object.assign(t,p);return copy(t);},
 sendMessage:async(id,m,opts)=>{findTab(id);if(ack==='missing')throw new Error('No receiver');return {ok:true,revision:ack==='stale'?m.snapshot?.revision-1:m.snapshot?.revision,guardId:'guard-document-0001',version:ack==='old'?'1.0.0':'2.0.0'};},
 onUpdated:event(),onCreated:event(),onAttached:event(),onActivated:event(),onRemoved:event(),onReplaced:event()},
 windows:{get:async(id,q={})=>{const w=copy(findWindow(id));if(q.populate)w.tabs=copy(tabs.filter(t=>t.windowId===id));return w;},
 getAll:async q=>windows.map(w=>({...copy(w),tabs:copy(tabs.filter(t=>t.windowId===w.id))})),
 create:async p=>{
   if(failure==='window-before')throw new Error('API failed before creation');
   const w={id:nextWindow++,type:'normal',incognito:false,focused:p.focused??true,state:'normal',left:0,top:0,width:900,height:700};windows.push(w);createdWindows.push({id:w.id,...p});
   let t;if(p.tabId){t=findTab(p.tabId);moveTab(t,w.id);}else t=createTab({windowId:w.id,url:p.url});
   if(failure==='window-after')throw new Error('Acknowledgement lost after creation');
   return {...copy(w),tabs:[copy(t)]};
 },
 update:async(id,p)=>{if(['maximized','fullscreen','minimized'].includes(p.state)&&['left','top','width','height'].some(k=>k in p))throw new Error('Invalid state/bounds combination');const w=findWindow(id);Object.assign(w,p);updates.push({windowId:id,...p});return copy(w);},onRemoved:event()},
 action:{setBadgeText:async p=>badge.push(p),setBadgeBackgroundColor:async()=>{},setTitle:async()=>{}},
 alarms:{create:async()=>{},clear:async()=>true,onAlarm:event()},contextMenus:{removeAll:async()=>{},create:()=>{},onClicked:event()},commands:{onCommand:event()},scripting:{executeScript:async()=>[]},
 webNavigation:{getFrame:async({tabId})=>({documentId:`document-${tabId}`,documentLifecycle:'active'}),onBeforeNavigate:event(),onCommitted:event(),onHistoryStateUpdated:event(),onReferenceFragmentUpdated:event()},
 permissions:{contains:async()=>permission},system:{display:{getInfo:async()=>[{id:'display-one',name:'Main display',isEnabled:true,isPrimary:true,workArea:{left:0,top:0,width:1920,height:1080}}]}}
};
function initial(){windows=[{id:1,type:'normal',incognito:false,state:'normal',focused:true,left:0,top:0,width:1920,height:1080}];tabs=Array.from({length:5},(_,i)=>({id:i+1,windowId:1,index:i,url:`https://dashboard${i+1}.example.com/`,title:`Dashboard ${i+1}`,pinned:i<4,active:i===0,incognito:false,token:`original-document-${i+1}`,scroll:701,formValue:'unfinished input'}));}
initial();await import('../../src/background/service-worker.js');
const S=await import('../../src/background/state.js'),WS=await import('../../src/background/workspace-state.js'),W=await import('../../src/background/workspaces.js');
await Promise.all([S.ready,WS.workspaceReady]);const listener=chrome.runtime.onMessage.listeners[0];
const sender={id,url:chrome.runtime.getURL('ui/workspaces.html')};
function send(m,s=sender){return new Promise(resolve=>{if(!listener(m,s,resolve))resolve({ignored:true});});}
function content(id=1){return {id:chrome.runtime.id,url:findTab(id).url,tab:copy(findTab(id)),documentId:`document-${id}`,frameId:0};}
const link=(n='one')=>({type:'ANCHOR_OPEN_LINK',kind:'link',url:'https://destination.example.com/report',intentId:'gesture-00000000-'+n});
const area={left:0,top:0,width:1920,height:1080};
function definition(count=4,layout='grid') {return {id:'workspace-one',name:'Operations desk',layout,destination:'browsing-window',foreground:false,reserved:true,displayId:'auto',gap:12,anchors:Array.from({length:count},(_,i)=>({id:'anchor-'+(i+1),label:'Dashboard '+(i+1),url:`https://dashboard${i+1}.example.com/`,mode:'strict'}))};}
async function reset(){
 failure='';ack='ok';permission=false;
 await send({type:'UI_RESET'});for(const k of Object.keys(stores.session))if(k.startsWith('tab:'))await S.forget(Number(k.slice(4)));
 initial();nextTab=100;nextWindow=10;createdTabs=[];createdWindows=[];moved=[];updates=[];badge=[];
}
async function open(count=4,layout='grid') {const w=definition(count,layout);assert.equal((await send({type:'UI_SAVE_WORKSPACE',workspace:w})).ok,true);return send({type:'UI_OPEN_WORKSPACE',workspaceId:w.id,area,adoptIds:Object.fromEntries(w.anchors.map((a,i)=>[a.id,i+1])),browsingWindowId:1});}

test('routing: new-window mode never navigates or recreates the source',async()=>{await reset();await send({type:'UI_SETTINGS',patch:{destination:'new-window',foreground:false}});const r=await send(link(),content());assert.equal(r.status,'opened');assert.equal(createdWindows.length,1);assert.equal(createdWindows[0].focused,false);assert.equal(findTab(1).token,'original-document-1');assert.equal(findTab(1).formValue,'unfinished input');});
test('routing: four concurrent sources share exactly one browsing-window creation',async()=>{await reset();await send({type:'UI_SETTINGS',patch:{destination:'browsing-window',foreground:false}});const r=await Promise.all([1,2,3,4].map(i=>send(link(String(i)),content(i))));assert(r.every(x=>x.status==='opened'));assert.equal(createdWindows.length,1);assert.equal(createdTabs.length,4);assert.equal(new Set(createdTabs.map(t=>t.windowId)).size,1);});
test('routing: selecting a destination window never overwrites a tab already there',async()=>{await reset();windows.push({id:2,type:'normal',incognito:false});tabs.push({id:6,windowId:2,url:'https://research.example.com/',token:'research-in-progress'});await send({type:'UI_SET_BROWSING_WINDOW',windowId:2});await send({type:'UI_SETTINGS',patch:{destination:'browsing-window'}});await send(link(),content());assert.equal(findTab(6).token,'research-in-progress');assert.equal(createdTabs[0].windowId,2);assert.equal(createdWindows.length,0);});
test('routing: closed destination is replaced only on the next deliberate link',async()=>{await reset();await send({type:'UI_SETTINGS',patch:{destination:'browsing-window'}});await send(link('a'),content());const id=WS.runtime.browsing.default;windows=windows.filter(w=>w.id!==id);tabs=tabs.filter(t=>t.windowId!==id);assert.equal(createdWindows.length,1);await send(link('b'),content());assert.equal(createdWindows.length,2);assert.notEqual(WS.runtime.browsing.default,id);});
test('routing: uncertain browser-window creation is not retried automatically or on a second gesture',async()=>{await reset();await send({type:'UI_SETTINGS',patch:{destination:'browsing-window'}});failure='window-after';assert.equal((await send(link('a'),content())).status,'uncertain');failure='';assert.equal((await send(link('b'),content())).status,'uncertain');assert.equal(createdWindows.length,1);assert(WS.runtime.operations['destination:default']);});
test('routing: explicit operation acknowledgement permits a later retry',async()=>{await reset();await send({type:'UI_SETTINGS',patch:{destination:'browsing-window'}});failure='window-before';await send(link('a'),content());failure='';await send({type:'UI_ACK_OPERATION',key:'destination:default'});assert.equal((await send(link('b'),content())).status,'opened');});
test('routing: private destination windows are rejected',async()=>{await reset();windows.push({id:2,type:'normal',incognito:true});const r=await send({type:'UI_SET_BROWSING_WINDOW',windowId:2});assert.equal(r.ok,false);});
test('solo: moves live tab, reserves only its new window, and preserves page state',async()=>{await reset();const r=await send({type:'UI_SOLO',tabId:1});assert.equal(r.ok,true);assert.equal(createdWindows.length,1);assert.equal(createdWindows[0].tabId,1);assert.equal(createdTabs.length,0);assert.equal(findTab(1).token,'original-document-1');assert.equal(tabs.filter(t=>t.windowId===findTab(1).windowId).length,1);assert.equal(WS.runtime.browsing[r.workspaceId],1);assert(WS.runtime.reserved[findTab(1).windowId]);});
test('workspace: four selected pages tile into four real windows without URL reloads',async()=>{await reset();const r=await open();assert.equal(r.ok,true,r.error);assert.equal(createdTabs.length,0);assert.equal(createdWindows.length,4);assert.equal(Object.keys(WS.runtime.reserved).length,4);for(let i=1;i<=4;i++){assert.equal(findTab(i).token,`original-document-${i}`);assert.equal(findTab(i).scroll,701);assert.equal(findTab(i).formValue,'unfinished input');}assert.equal(findTab(5).windowId,1);assert.deepEqual(r.runtime.runs['workspace-one'].lastLayout.bounds[3].requested,{left:966,top:546,width:954,height:534});});
test('workspace: reopening reuses known live bindings rather than matching URLs or creating duplicates',async()=>{await reset();await open();const count=createdWindows.length;const r=await send({type:'UI_OPEN_WORKSPACE',workspaceId:'workspace-one',area});assert.equal(r.ok,true,r.error);assert.equal(createdWindows.length,count);assert.equal(createdTabs.length,0);});
test('workspace: collection moves chosen anchors together but never moves an unrelated page',async()=>{await reset();const r=await open(4,'collection');assert.equal(r.ok,true,r.error);assert.equal(new Set([1,2,3,4].map(id=>findTab(id).windowId)).size,1);assert.equal(findTab(5).windowId,1);assert.equal(createdWindows.length,1);assert.equal(createdTabs.length,0);});
test('workspace: tiny work area rejected before any page or window moves',async()=>{await reset();await send({type:'UI_SAVE_WORKSPACE',workspace:definition()});const r=await send({type:'UI_OPEN_WORKSPACE',workspaceId:'workspace-one',area:{left:0,top:0,width:800,height:600}});assert.equal(r.ok,false);assert.equal(createdWindows.length,0);assert.equal(moved.length,0);});
test('workspace: arrange-only never reopens closed anchors',async()=>{await reset();await open();tabs=tabs.filter(t=>t.id!==1);await W.onClosed(1);const before=createdWindows.length;const r=await send({type:'UI_OPEN_WORKSPACE',workspaceId:'workspace-one',area,arrangeOnly:true});assert.equal(r.ok,false);assert.equal(createdWindows.length,before);});
test('workspace: explicit Open recreates a closed anchor from its saved URL',async()=>{await reset();await open();tabs=tabs.filter(t=>t.id!==1);await W.onClosed(1);const before=createdTabs.length;const r=await send({type:'UI_OPEN_WORKSPACE',workspaceId:'workspace-one',area});assert.equal(r.ok,true,r.error);assert.equal(createdTabs.length,before+1);assert.equal(createdTabs.at(-1).url,'https://dashboard1.example.com/');});
test('workspace: release restores prior protection choices without closing or reloading',async()=>{await reset();await send({type:'UI_TAB',tabId:1,action:'unprotect'});await open(1);const n=tabs.length,token=findTab(1).token;await send({type:'UI_RELEASE_WORKSPACE',workspaceId:'workspace-one'});assert.equal(tabs.length,n);assert.equal(findTab(1).token,token);assert.equal(S.recordFor(findTab(1)).override,false);assert.equal(Object.keys(WS.runtime.reserved).length,0);});
test('workspace: delete removes definition and releases membership, not browser objects',async()=>{await reset();await open();const n=tabs.length;await send({type:'UI_DELETE_WORKSPACE',workspaceId:'workspace-one'});assert.equal(WS.library.items.length,0);assert.equal(tabs.length,n);assert.equal(Object.keys(WS.runtime.reserved).length,0);});
test('workspace: candidate native new tab moves intact to the chosen browsing destination',async()=>{await reset();await open();const src=findTab(1).windowId;const extra=createTab({windowId:src,url:'https://details.example.com/',active:false,openerTabId:1});extra.token='native-navigation';const n=createdTabs.length;await W.observeNewTab(copy(extra));assert.equal(findTab(extra.id).windowId,1);assert.equal(findTab(extra.id).token,'native-navigation');assert.equal(createdTabs.length,n);assert.equal(WS.runtime.branches[extra.id].sourceId,1);});
test('workspace: blank native tab waits for a knowable URL rather than replaying it',async()=>{await reset();await open();const src=findTab(1).windowId,extra=createTab({windowId:src,url:'about:blank'});await W.observeNewTab(copy(extra));assert.equal(findTab(extra.id).windowId,src);extra.url='https://details.example.com/';await W.processCandidate(extra.id);assert.equal(findTab(extra.id).windowId,1);});
test('workspace: likely auth tabs remain in place with an explanation',async()=>{await reset();await open();const src=findTab(1).windowId,extra=createTab({windowId:src,url:'https://accounts.google.com/login'});await W.observeNewTab(copy(extra));assert.equal(findTab(extra.id).windowId,src);assert.match(WS.runtime.runs['workspace-one'].notice,/sign-in/);});
test('workspace: pause suspends both link protection and extra-tab relocation',async()=>{await reset();await open();await send({type:'UI_PAUSE_WORKSPACE',workspaceId:'workspace-one'});assert.equal((await send(link(),content())).status,'native');const src=findTab(1).windowId,extra=createTab({windowId:src,url:'https://details.example.com/'});await W.observeNewTab(copy(extra));assert.equal(findTab(extra.id).windowId,src);await send({type:'UI_PAUSE_WORKSPACE',workspaceId:'workspace-one',resume:true});assert.equal((await send(link('b'),content())).status,'opened');});
test('workspace: no creation listener resurrects a closed anchor',async()=>{await reset();await open();const n=createdWindows.length;tabs=tabs.filter(t=>t.id!==1);await W.onClosed(1);assert.equal(createdWindows.length,n);assert.equal(WS.runtime.runs['workspace-one'].anchors['anchor-1'],undefined);});
test('workspace: user dragging an anchor out releases it rather than snapping it back',async()=>{await reset();await open();await WS.updateRuntime(r=>{r.moves={};});moveTab(findTab(1),1);const n=moved.length;await W.onAttached(1,{newWindowId:1,newPosition:0});assert.equal(S.recordFor(findTab(1)).workspaceId,undefined);assert.equal(moved.length,n);});
test('workspace: extension-owned move token prevents false release',async()=>{await reset();await open();const binding=WS.runtime.runs['workspace-one'].anchors['anchor-1'];await W.onAttached(1,{newWindowId:findTab(1).windowId,newPosition:0});assert.equal(WS.runtime.runs['workspace-one'].anchors['anchor-1'],binding);});
test('workspace: reserved window cannot also become a browsing target',async()=>{await reset();await open();const r=await send({type:'UI_SET_BROWSING_WINDOW',workspaceId:'workspace-one',windowId:findTab(1).windowId});assert.equal(r.ok,false);});
test('workspace: public page content cannot create or delete workspaces',async()=>{await reset();const r=await send({type:'UI_SAVE_WORKSPACE',workspace:definition()},content());assert.equal(r.ignored,true);assert.equal(WS.library.items.length,0);});
test('workspace: import validates fully before releasing live workspace',async()=>{await reset();await open();const r=await send({type:'UI_IMPORT_WORKSPACES',library:{schemaVersion:99,items:[]}});assert.equal(r.ok,false);assert.equal(Object.keys(WS.runtime.reserved).length,4);});
test('workspace: valid import releases old bindings but never auto-opens imported URLs',async()=>{await reset();await open();const n=createdTabs.length;const r=await send({type:'UI_IMPORT_WORKSPACES',library:{schemaVersion:1,items:[{...definition(1),id:'new-workspace'}]}});assert.equal(r.ok,true);assert.equal(createdTabs.length,n);assert.equal(Object.keys(WS.runtime.reserved).length,0);});
test('workspace: optional display denial falls back to user-provided work area',async()=>{await reset();assert.deepEqual(await W.displayInfo(),[]);const r=await open();assert.equal(r.ok,true);});
test('workspace: vanished saved display falls back to primary with visible warning',async()=>{await reset();permission=true;await send({type:'UI_SAVE_WORKSPACE',workspace:{...definition(1),displayId:'missing-screen'}});const r=await send({type:'UI_OPEN_WORKSPACE',workspaceId:'workspace-one',area});assert.equal(r.ok,true,r.error);assert.match(r.outcome.warnings.join(' '),/primary/);});
test('workspace: runtime bindings rehydrate from session storage on module restart',async()=>{await reset();await open();const again=await import('../../src/background/workspace-state.js?restart='+Date.now());await again.workspaceReady;assert.deepEqual(again.runtime.runs['workspace-one'].anchors,WS.runtime.runs['workspace-one'].anchors);assert.equal(again.library.items[0].name,'Operations desk');});
test('source: return to anchor uses session provenance, not URL guessing',async()=>{await reset();await send(link(),content());const branch=createdTabs[0];const r=await send({type:'UI_RETURN_SOURCE',tabId:branch.id});assert.equal(r.ok,true);assert(updates.some(u=>u.id===1&&u.active===true));});
test('source: closed original is reported and not recreated',async()=>{await reset();await send(link(),content());const branch=createdTabs[0];tabs=tabs.filter(t=>t.id!==1);const n=createdTabs.length;const r=await send({type:'UI_RETURN_SOURCE',tabId:branch.id});assert.equal(r.ok,false);assert.match(r.error,/closed/);assert.equal(createdTabs.length,n);});
test('health: badge ready requires a versioned document-targeted guard acknowledgement',async()=>{await reset();const r=await send({type:'UI_STATE',tabId:1});assert.equal(r.connected,true);assert.equal(r.health.status,'ready');assert.equal(badge.at(-1).text,'ON');});
for(const bad of ['missing','stale','old'])test(`health: ${bad} acknowledgement cannot show a green-ready ON badge`,async()=>{await reset();ack=bad;const r=await send({type:'UI_STATE',tabId:1});assert.equal(r.connected,false);assert.equal(r.health.status,'unavailable');assert.equal(badge.at(-1).text,'!');});
test('health: snapshot revisions increase on pin state changes',async()=>{await reset();const a=await send({type:'UI_STATE',tabId:1});findTab(1).pinned=false;const b=await send({type:'UI_STATE',tabId:1});assert(b.snapshot.revision>a.snapshot.revision);assert.equal(b.snapshot.active,false);});
test('health: stale HELLO from replaced document is rejected',async()=>{await reset();const s=content();s.documentId='obsolete-document';const r=await send({type:'ANCHOR_HELLO',guardId:'guard-instance-0001'},s);assert.equal(r.ok,false);});
test('health: acknowledged current HELLO can establish ready state',async()=>{await reset();const s=content(),hello=await send({type:'ANCHOR_HELLO',guardId:'guard-instance-0001'},s);assert.equal(hello.ok,true);await send({type:'ANCHOR_ACK',guardId:'guard-instance-0001',revision:hello.snapshot.revision},s);assert.equal(S.recordFor(findTab(1)).health.status,'ready');});

test('workspace: one live tab cannot be bound to two saved anchors',async()=>{await reset();const d=definition(2);d.anchors[1].url=d.anchors[0].url;await send({type:'UI_SAVE_WORKSPACE',workspace:d});const r=await send({type:'UI_OPEN_WORKSPACE',workspaceId:d.id,adoptIds:{'anchor-1':1,'anchor-2':1},area});assert.equal(r.ok,false);assert.match(r.error,/distinct/);assert.equal(createdWindows.length,0);assert.equal(moved.length,0);});
test('workspace: release queues behind an in-progress open instead of leaking reservations',async()=>{await reset();await send({type:'UI_SAVE_WORKSPACE',workspace:definition()});const [o,r]=await Promise.all([send({type:'UI_OPEN_WORKSPACE',workspaceId:'workspace-one',adoptIds:{'anchor-1':1,'anchor-2':2,'anchor-3':3,'anchor-4':4},area}),send({type:'UI_RELEASE_WORKSPACE',workspaceId:'workspace-one'})]);assert.equal(o.ok,true);assert.equal(r.ok,true);assert.equal(Object.keys(WS.runtime.reserved).length,0);assert.equal(S.recordFor(findTab(1)).workspaceId,undefined);});
test('workspace: extension move lease is consumed so a following manual drag releases immediately',async()=>{await reset();await open();await W.onAttached(1,{newWindowId:findTab(1).windowId,newPosition:0});moveTab(findTab(1),1);await W.onAttached(1,{newWindowId:1,newPosition:0});assert.equal(S.recordFor(findTab(1)).workspaceId,undefined);});
test('workspace: native tabs respect separate-new-window routing without replay',async()=>{await reset();await open();await send({type:'UI_SAVE_WORKSPACE',workspace:{...definition(),destination:'new-window'}});const sourceWindow=findTab(1).windowId,extra=createTab({windowId:sourceWindow,url:'https://detail.example.com/',openerTabId:1});const before=createdTabs.length;await W.observeNewTab(copy(extra));assert.notEqual(findTab(extra.id).windowId,sourceWindow);assert.notEqual(findTab(extra.id).windowId,1);assert.equal(createdTabs.length,before);assert.equal(createdWindows.at(-1).tabId,extra.id);});
test('workspace: removed anchor can be re-added on the same live tab without losing its new binding',async()=>{await reset();await open(1);const token=findTab(1).token;const next=definition(1);next.anchors[0].id='anchor-readded';next.anchors[0].label='Re-added dashboard';await send({type:'UI_SAVE_WORKSPACE',workspace:next});const result=await send({type:'UI_OPEN_WORKSPACE',workspaceId:next.id,adoptIds:{'anchor-readded':1},area});assert.equal(result.ok,true,result.error);assert.equal(findTab(1).token,token);assert.equal(S.recordFor(findTab(1)).workspaceId,next.id);assert.equal(S.recordFor(findTab(1)).anchorId,'anchor-readded');assert.equal(WS.runtime.runs[next.id].anchors['anchor-1'],undefined);assert.equal(WS.runtime.runs[next.id].anchors['anchor-readded'],1);assert(WS.runtime.reserved[findTab(1).windowId].members.includes(1));const windowsBefore=createdWindows.length;const reopened=await send({type:'UI_OPEN_WORKSPACE',workspaceId:next.id,area});assert.equal(reopened.ok,true,reopened.error);assert.equal(createdWindows.length,windowsBefore);});
test('workspace: arrange-only preflights every selected page before adopting any',async()=>{await reset();const d=definition(2);await send({type:'UI_SAVE_WORKSPACE',workspace:d});const result=await send({type:'UI_OPEN_WORKSPACE',workspaceId:d.id,adoptIds:{'anchor-1':1,'anchor-2':5},area});assert.equal(result.ok,false);assert.match(result.error,/changed/);assert.equal(S.recordFor(findTab(1)).workspaceId,undefined);assert.equal(createdWindows.length,0);assert.equal(moved.length,0);});
test('workspace: definite failed move clears ownership before a later manual drag',async()=>{await reset();await open(4,'collection');const reservedWindow=findTab(1).windowId;await send({type:'UI_SAVE_WORKSPACE',workspace:definition(4,'grid')});failure='window-before';const failed=await send({type:'UI_OPEN_WORKSPACE',workspaceId:'workspace-one',area});assert.equal(failed.ok,false);assert.equal(findTab(1).windowId,reservedWindow);assert.equal(Object.keys(WS.runtime.operations).some(key=>key.startsWith('move:')),false);failure='';moveTab(findTab(1),1);await W.onAttached(1,{newWindowId:1,newPosition:0});assert.equal(S.recordFor(findTab(1)).workspaceId,undefined);});
test('workspace: arrange-only preserves tab and workspace pause deadlines',async()=>{await reset();await open(1);await send({type:'UI_PAUSE_WORKSPACE',workspaceId:'workspace-one'});const runPause=WS.runtime.runs['workspace-one'].pausedUntil,tabPause=S.recordFor(findTab(1)).pausedUntil;const result=await send({type:'UI_OPEN_WORKSPACE',workspaceId:'workspace-one',area,arrangeOnly:true});assert.equal(result.ok,true,result.error);assert.equal(WS.runtime.runs['workspace-one'].pausedUntil,runPause);assert.equal(S.recordFor(findTab(1)).pausedUntil,tabPause);assert.equal((await send(link(),content())).status,'native');});
test('workspace: cannot adopt a page from a different reserved window',async()=>{await reset();await open(1);const reservedWindow=findTab(1).windowId,extra=createTab({windowId:reservedWindow,url:'https://dashboard2.example.com/',active:false});const other={...definition(1),id:'workspace-two',name:'Other desk',anchors:[{...definition(1).anchors[0],id:'anchor-two',url:extra.url}]};await send({type:'UI_SAVE_WORKSPACE',workspace:other});const result=await send({type:'UI_OPEN_WORKSPACE',workspaceId:other.id,adoptIds:{'anchor-two':extra.id},area});assert.equal(result.ok,false);assert.match(result.error,/another workspace window/);assert.equal(S.recordFor(extra).workspaceId,undefined);assert.deepEqual(WS.runtime.reserved[reservedWindow].members,[1]);assert.equal(WS.runtime.runs[other.id],undefined);});
test('workspace: invalid saved runtime is sanitized and rebuilt from live bindings at startup',async()=>{await reset();await open(1);const liveWindow=findTab(1).windowId;stores.session.workspaceRuntime={runs:{'workspace-one':{anchors:{'anchor-1':9999,unknown:1},pausedUntil:Date.now()+90*24*60*60*1000,lastLayout:'bad'},'ghost-workspace':{anchors:{a:1}}},reserved:{[liveWindow]:{workspaceId:'ghost-workspace',members:[9999],foreground:'yes'},'9999':{workspaceId:'workspace-one',members:[1]}},browsing:{default:9999,'workspace-one':liveWindow},branches:{'9999':{sourceId:1,at:Date.now()}},moves:{'1':Date.now()+15000},operations:{'destination:workspace-one':{status:'pending',at:Date.now(),label:'Keep pending'},bad:{status:'done'}},candidates:{'9999':{windowId:9999,workspaceId:'workspace-one',at:Date.now()}}};const restored=await import('../../src/background/workspace-state.js?startup='+Date.now());await restored.workspaceReady;assert.deepEqual(restored.runtime.runs['workspace-one'].anchors,{'anchor-1':1});assert(restored.runtime.runs['workspace-one'].pausedUntil<=Date.now()+330000);assert.equal(restored.runtime.runs['ghost-workspace'],undefined);assert.deepEqual(restored.runtime.reserved[liveWindow].members,[1]);assert.equal(restored.runtime.reserved[9999],undefined);assert.equal(restored.runtime.browsing.default,undefined);assert.equal(restored.runtime.browsing['workspace-one'],undefined);assert.equal(restored.runtime.branches[9999],undefined);assert.equal(restored.runtime.moves[1],undefined);assert.equal(restored.runtime.operations['destination:workspace-one'].status,'pending');assert.equal(restored.runtime.operations.bad,undefined);assert.equal(restored.runtime.candidates[9999],undefined);});
test('workspace: startup releases cross-workspace anchors sharing a reserved window',async()=>{await reset();const first=definition(1),second={...definition(1),id:'workspace-two',name:'Other desk',anchors:[{...definition(1).anchors[0],id:'anchor-two',url:'https://dashboard2.example.com/'}]};await send({type:'UI_SAVE_WORKSPACE',workspace:first});await send({type:'UI_SAVE_WORKSPACE',workspace:second});for(const [tabId,workspaceId,anchorId]of [[1,first.id,'anchor-1'],[2,second.id,'anchor-two']]){const tab=findTab(tabId),record={...S.recordFor(tab),workspaceId,anchorId,beforeWorkspace:{override:false},override:true,mode:'strict',homeUrl:tab.url,destination:'browsing-window',foreground:false};await S.persist(tabId,record);}stores.session.workspaceRuntime={runs:{'workspace-one':{anchors:{'anchor-1':1}},'workspace-two':{anchors:{'anchor-two':2}}},reserved:{},browsing:{},branches:{},moves:{},operations:{},candidates:{}};const sameWindow=findTab(1).windowId,restored=await import('../../src/background/workspace-state.js?conflict='+Date.now());await restored.workspaceReady;assert.equal(findTab(1).windowId,sameWindow);assert.equal(findTab(2).windowId,sameWindow);assert.equal(S.recordFor(findTab(1)).workspaceId,undefined);assert.equal(S.recordFor(findTab(2)).workspaceId,undefined);assert.equal(Object.keys(restored.runtime.reserved).length,0);assert.equal(Object.keys(restored.runtime.runs['workspace-one'].anchors).length,0);assert.equal(Object.keys(restored.runtime.runs['workspace-two'].anchors).length,0);assert.match(restored.runtime.runs['workspace-one'].notice,/shared a window/);assert.match(restored.runtime.runs['workspace-two'].notice,/shared a window/);});
for(const dangerous of ['__proto__','constructor','prototype','default','toString','valueOf','hasOwnProperty'])test(`workspace: reserved identity ${dangerous} is rejected before persistence`,async()=>{await reset();const r=await send({type:'UI_SAVE_WORKSPACE',workspace:{...definition(),id:dangerous}});assert.equal(r.ok,false);assert.equal(WS.library.items.length,0);});
